name: Hugo Server

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  hugo_server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Hugo
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.125.4/hugo_extended_0.125.4_Linux-64bit.deb
          sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Run Hugo server
        run: |
          hugo server -D --themesDir=../.. --source=src --bind 0.0.0.0

